### ISSUE TITLE
Services Provided

### ISSUE THREAD

**Issue by MaxAlmeida** [lappis-tools/chef-lappis#13]
Explain about the serviçes provided by LAPPIS:
- [x] Redmine  
- [x] Dotproject
- [x] Boca
- [x] Moodle
- [x] Firewall
- [x] Rocket.Chat
- [x] Hubot

**Comment by ArthurJahn** [comment]
I believe it's done. See [here](https://github.com/lappis-tools/chef-lappis/wiki/Available-Services).
