### ISSUE TITLE
Change template of the Virtual Machines that have external access

### ISSUE THREAD

**Issue by MaxAlmeida** [lappis-tools/chef-lappis#9]
In the virtual machines that have external access, is necessary to modify it's templates to add external access route.

Virtual machines:  
- [ ] Services  
- [ ] Boca  
- [ ] Moodle  
- [ ] Redmine  
- [ ] Dotproject

**Comment by luanguimaraesla** [comment]
Unnecessary, now there is a script tha handle the external routes to these VM's
